name: run make.py

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        # For example, using `pytest`
        run: |
            uv run make.py train --config configs/intro-figure.toml --n-step 1
            uv run make.py train --config configs/feature-geometry.toml --n-step 1
            uv run make.py train --config configs/varying-sparsity.toml --n-step 1
